### ISSUE TITLE
Issue while updating github

### ISSUE THREAD

**Issue by lcalvy** [transifex/txgh#42]
Hi,
I have noticed an error in console after uptating github when I test a transifex webhook call.

```
web_1 | I, [Tue 26-01-2016 0816 #1]  INFO -- : Processing request at /hooks/transifex
web_1 | I, [Tue 26-01-2016 0816 #1]  INFO -- : #<Sinatra::Request:0x00559c30fc1cd8 @env={"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"/hooks", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"2.15.3", "GATEWAY_INTERFACE"=>"CGI/1.2", "REQUEST_METHOD"=>"POST", "REQUEST_PATH"=>"/hooks/transifex", "REQUEST_URI"=>"/hooks/transifex", "HTTP_VERSION"=>"HTTP/1.1", "HTTP_HOST"=>"localhost:8080", "HTTP_CONNECTION"=>"keep-alive", "CONTENT_LENGTH"=>"76", "HTTP_AUTHORIZATION"=>"Basic xxxxxxxxx==", "HTTP_CACHE_CONTROL"=>"no-cache", "HTTP_ORIGIN"=>"chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop", "CONTENT_TYPE"=>"application/x-www-form-urlencoded", "HTTP_USER_AGENT"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36", "HTTP_POSTMAN_TOKEN"=>"540316de-9e81-67b8-0cab-500336c6c317", "HTTP_ACCEPT"=>"*/*", "HTTP_ACCEPT_ENCODING"=>"gzip, deflate", "HTTP_ACCEPT_LANGUAGE"=>"fr-FR,fr;q=0.8,en;q=0.6", "SERVER_NAME"=>"localhost", "SERVER_PORT"=>"8080", "PATH_INFO"=>"/transifex", "REMOTE_ADDR"=>"10.0.2.2", "puma.socket"=>#<TCPSocket:fd 12>, "rack.hijack?"=>true, "rack.hijack"=>#<Puma::Client:0x2ace187e1a88 @ready=true>, "rack.input"=>#<StringIO:0x00559c30fc2ca0>, "rack.url_scheme"=>"http", "rack.after_reply"=>[], "rack.request.query_string"=>"", "rack.request.query_hash"=>{}, "rack.request.form_hash"=>{"project"=>"coorpacademy/mooc-core", "resource"=>"account", "language"=>"it", "translated"=>"100"}, "rack.request.form_vars"=>"project=coorpacademy%2Fmooc-core&resource=account&language=it&translated=100", "rack.request.form_input"=>#<StringIO:0x00559c30fc2ca0>, "sinatra.route"=>"POST /transifex"}, @params={"project"=>"coorpacademy/mooc-core", "resource"=>"account", "language"=>"it", "translated"=>"100"}>
web_1 | I, [Tue 26-01-2016 0816 #1]  INFO -- : account
web_1 | I, [Tue 26-01-2016 0816 #1]  INFO -- : request language matches resource
web_1 | I, [2016-01-26T08:16:10.082753 #1]  INFO -- : get https://www.transifex.com/api/2/project/mooc-core/resource/account/translation/it/
web_1 | D, [2016-01-26T08:16:10.083611 #1] DEBUG -- request: User-Agent: "Faraday v0.9.2"
web_1 | Authorization: "Basic xxxxxxxxxxx"
web_1 | Accept: "application/json"
web_1 | I, [2016-01-26T08:16:10.321601 #1]  INFO -- Status: 200
web_1 | D, [2016-01-26T08:16:10.322363 #1] DEBUG -- response: server: "nginx"
web_1 | vary: "Accept-Encoding, Authorization, Host, Accept-Language, Cookie"
web_1 | cache-control: "max-age=0"
web_1 | content-type: "application/json; charset=utf-8"
web_1 | date: "Tue, 26 Jan 2016 08:16:10 GMT"
web_1 | expires: "Tue, 26 Jan 2016 08:16:10 GMT"
web_1 | transfer-encoding: "chunked"
web_1 | content-language: "en"
web_1 | x-content-type-options: "nosniff"
web_1 | connection: "close"
web_1 | set-cookie: "X-Mapping-fjhppofk=B8558B7BB369B761FC4CE03884ACF0F5; path=/"
web_1 | last-modified: "Tue, 26 Jan 2016 08:16:10 GMT"
web_1 | x-frame-options: "SAMEORIGIN"
web_1 | I, [Tue 26-01-2016 0816 #1]  INFO -- : request language is in lang_map and is in request or is nil
web_1 | I, [Tue 26-01-2016 0816 #1]  INFO -- : make github commit for branch: heads/txgh
web_1 | 2016-01-26 08:16:13 +0000: Read error: #<NoMethodError: undefined method `bytesize' for [:ref, "refs/heads/txgh"]:Array>
web_1 | /usr/local/bundle/gems/puma-2.15.3/lib/puma/server.rb:668:in `block in handle_request'
web_1 | /usr/local/bundle/gems/sawyer-0.6.0/lib/sawyer/resource.rb:125:in `each'
web_1 | /usr/local/bundle/gems/sawyer-0.6.0/lib/sawyer/resource.rb:125:in `each'
web_1 | /usr/local/bundle/gems/puma-2.15.3/lib/puma/server.rb:666:in `handle_request'
web_1 | /usr/local/bundle/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
web_1 | /usr/local/bundle/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
web_1 | /usr/local/bundle/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `call'
web_1 | /usr/local/bundle/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

You can reproduce on this Docker image, https://hub.docker.com/r/coorpacademy/txgh/

* Ruby 2.18
* Git 2.1.4
* Puma 2.15.3

Github seems to have been updated and there is no response from txgh.

**Comment by matthewjackowski** [comment]
Hi @lcalvy I pulled your docker image and ran the project tests...this seemed to work ok.  So my initial feeling is that this issue is the result of some of the config not being setup right. ie 'undefined bytesize' because an expected file is missing or maybe even something wrong with the repo.

I will dig more and see if I can recreate a case where this might happen.  

Of course the ultimate *best* is if you can help identify a specific payload that is missing 'bytesize'...and then we can write a test for it!

**Comment by matthewjackowski** [comment]
I haven't been able to recreate this issue under proper configuration.  Closing issue.
