### ISSUE TITLE
Could be a configuration problem: NoMethodError - undefined method `info' for nil:NilClass: 

### ISSUE THREAD

**Issue by hassanshaikley** [transifex/txgh#61]
Setting up TXGH and I am getting this error after I translate something on Transifex. Note that the Github -> TXGH post request works and updates my TXGH resource:

`NoMethodError - undefined method `info' for nil:NilClass:

Was wondering if this is a bug or an issue with something that I am doing. I am using ruby 2.2.0 on Ubuntu 16

```
2016-08-09 15:20:41 - NoMethodError - undefined method `info' for nil:NilClass:
	/root/txgh/lib/txgh/handlers/transifex_hook_handler.rb:11:in `initialize'
	/root/txgh/lib/txgh/app.rb:135:in `new'
	/root/txgh/lib/txgh/app.rb:135:in `transifex_handler_for'
	/root/txgh/lib/txgh/app.rb:67:in `block in <class:Hooks>'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
	/root/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by nsiddarthreddy** [comment]
@hassanshaikley  you are right, its a configuration issue in this [file](https://github.com/transifex/txgh/blob/master/config/txgh.yml). To be more specific please check the project configs.

**Comment by hassanshaikley** [comment]
How can I know which part has the error? It would be nice if there were better error messages.

Can I push to an organizations repo using txgh? Could that being unsupported be the issue?

**Comment by matthewjackowski** [comment]
Hi,
The important bit is here:
/root/txgh/lib/txgh/handlers/transifex_hook_handler.rb:11:in `initialize'
So when you look here:
https://github.com/transifex/txgh/blob/master/lib/txgh/handlers/transifex_hook_handler.rb#L11

You'll see that we are trying to initialize the class with the values passed in as options.  In this case it's most likely that some config is incorrect/missing.

Logging/error messaging here is a bit tricky here because this happens before the local logger is instantiated.  My thoughts here is that maybe a 'validate config' rake task might be more appropriate.

I'm not aware of an specific issue with using Txgh with orgs, other than you need to be sure that permissions are set correctly in order to enable Txgh.  If you do find something feel free to log an issue for it and I'll take a look.

Also, note that we accepted Pull Requests, so if you any specific improvements I'd be happy to take them on!
