### ISSUE TITLE
Getting an error on AWS

### ISSUE THREAD

**Issue by croneter** [transifex/txgh#77]
Hi there

I get a txgh error when the github side fires: 
```

192.30.252.34 - - [17/Apr/2017:18:40:12 +0000] "POST /hooks/github HTTP/1.1" 500 229964 0.3245
I, [Mon 17-04-2017 1840 #16255]  INFO -- : Processing request at /hooks/github
I, [Mon 17-04-2017 1840 #16255]  INFO -- : processing payload from form
2017-04-17 18:40:12 - Psych::SyntaxError - (<unknown>): did not find expected key while parsing a block mapping at line 22 column 9:
        /home/ec2-user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse'
        /home/ec2-user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
        /home/ec2-user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych.rb:318:in `parse'
        /home/ec2-user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych.rb:245:in `load'
        /home/ec2-user/txgh/lib/txgh/key_manager.rb:43:in `yaml'
        /home/ec2-user/txgh/lib/txgh/key_manager.rb:53:in `repo_config_for'
        /home/ec2-user/txgh/lib/txgh/key_manager.rb:17:in `config_from_repo'
        /home/ec2-user/txgh/lib/txgh/app.rb:104:in `block in <class:Hooks>'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/urlmap.rb:66:in `block in call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `each'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/tempfile_reaper.rb:15:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/lint.rb:49:in `_call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/lint.rb:37:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/showexceptions.rb:24:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/chunked.rb:54:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `call'
        /home/ec2-user/.rvm/gems/ruby-2.2.2/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```
Any ideas?

**Comment by croneter** [comment]
Using latest txgh commit https://github.com/transifex/txgh/commit/ed8e4bebf21e873b9f4ae6f3b41aa74a5cf5f83c, trying to follow https://docs.transifex.com/integrations/github (which seems outdated) and https://github.com/transifex/txgh/issues/14

**Comment by croneter** [comment]
My txgh.yml looks like this:
```
txgh:
  github:
    repos:
      croneter/PlexKodiConnect:
        api_username: "username"
        api_token: "token"
        push_source_to: "PlexKodiConnect"
        branch: "translations_transifex"
        webhook_secret: "secrect"
  transifex:
    projects:
      PlexKodiConnect:
        tx_config: "/home/ec2-user/tx.config"
        api_username: "username"
        api_password: "token"
        push_translations_to: "croneter/PlexKodiConnect"
        # push_trigger: "<%= ENV['TX_PUSH_TRIGGER_REVIEWED_OR_TRANSLATED'] %>"
        # webhook_secret: "<%= ENV['TX_WEBHOOK_SECRET'] %>"
```

Issue seems to stem from line 103 in app.rb, currently reading
```
github_repo_name = "#{payload['repository']['owner']['name']}/#{payload['repository']['name']}"
```
This gives me a string `/PlexKodiConnect`. Looking at my (unchanged/standard) Github webhook, I don't receive the 'owner'-'name', this should rather be
```
github_repo_name = "#{payload['repository']['full_name']}"
```
which results in `croneter/PlexKodiConnect`. However, I'm still getting the same error. Any ideas?

**Comment by matthewjackowski** [comment]
At a high level, there clearly is a mapping problem between the webhook coming from GitHub and your configuration.  That said there is a certain amount of variability in how you can configure GitHub webhooks (yes agreed the documentation is lacking here, so doc improvements are always welcome!).

I tried to account for these different edge cases, but it looks like your specific setup might be falling through.  I think that if the existing code is missing some keys, its likely that other assumptions about the response are invalid as well.

Here's what I suggest, if you can post an example response from your GitHub webhook (removing any private bits), I can add it to the test suite and make sure that Txgh properly supports this scenario.

**Comment by croneter** [comment]
Thanks for looking into this! 

I haven't configured the Github "standard" webhook at all, so I wouldn't consider this an edge case ;-). 

Webhook example: 
```
{
  "zen": "Speak like a human.",
  "hook_id": <hook-id>,
  "hook": {
    "type": "Repository",
    "id": <hook-id>,
    "name": "web",
    "active": true,
    "events": [
      "push"
    ],
    "config": {
      "content_type": "json",
      "insecure_ssl": "0",
      "url": "http://<URL>.compute.amazonaws.com:9292/hooks/github"
    },
    "updated_at": "2017-04-17T15:26:59Z",
    "created_at": "2017-04-17T15:26:59Z",
    "url": "https://api.github.com/repos/croneter/PlexKodiConnect/hooks/<hook-id>",
    "test_url": "https://api.github.com/repos/croneter/PlexKodiConnect/hooks/<hook-id>/test",
    "ping_url": "https://api.github.com/repos/croneter/PlexKodiConnect/hooks/<hook-id>/pings",
    "last_response": {
      "code": null,
      "status": "unused",
      "message": null
    }
  },
  "repository": {
    "id": <REPO ID>,
    "name": "PlexKodiConnect",
    "full_name": "croneter/PlexKodiConnect",
    "owner": {
      "login": "croneter",
      "id": <Github user id>,
      "avatar_url": "https://avatars0.githubusercontent.com/u/<Github user id>?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/croneter",
      "html_url": "https://github.com/croneter",
      "followers_url": "https://api.github.com/users/croneter/followers",
      "following_url": "https://api.github.com/users/croneter/following{/other_user}",
      "gists_url": "https://api.github.com/users/croneter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/croneter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/croneter/subscriptions",
      "organizations_url": "https://api.github.com/users/croneter/orgs",
      "repos_url": "https://api.github.com/users/croneter/repos",
      "events_url": "https://api.github.com/users/croneter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/croneter/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/croneter/PlexKodiConnect",
    "description": "Plex add-on for Kodi",
    "fork": true,
    "url": "https://api.github.com/repos/croneter/PlexKodiConnect",
    "forks_url": "https://api.github.com/repos/croneter/PlexKodiConnect/forks",
    "keys_url": "https://api.github.com/repos/croneter/PlexKodiConnect/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/croneter/PlexKodiConnect/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/croneter/PlexKodiConnect/teams",
    "hooks_url": "https://api.github.com/repos/croneter/PlexKodiConnect/hooks",
    "issue_events_url": "https://api.github.com/repos/croneter/PlexKodiConnect/issues/events{/number}",
    "events_url": "https://api.github.com/repos/croneter/PlexKodiConnect/events",
    "assignees_url": "https://api.github.com/repos/croneter/PlexKodiConnect/assignees{/user}",
    "branches_url": "https://api.github.com/repos/croneter/PlexKodiConnect/branches{/branch}",
    "tags_url": "https://api.github.com/repos/croneter/PlexKodiConnect/tags",
    "blobs_url": "https://api.github.com/repos/croneter/PlexKodiConnect/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/croneter/PlexKodiConnect/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/croneter/PlexKodiConnect/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/croneter/PlexKodiConnect/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/croneter/PlexKodiConnect/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/croneter/PlexKodiConnect/languages",
    "stargazers_url": "https://api.github.com/repos/croneter/PlexKodiConnect/stargazers",
    "contributors_url": "https://api.github.com/repos/croneter/PlexKodiConnect/contributors",
    "subscribers_url": "https://api.github.com/repos/croneter/PlexKodiConnect/subscribers",
    "subscription_url": "https://api.github.com/repos/croneter/PlexKodiConnect/subscription",
    "commits_url": "https://api.github.com/repos/croneter/PlexKodiConnect/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/croneter/PlexKodiConnect/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/croneter/PlexKodiConnect/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/croneter/PlexKodiConnect/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/croneter/PlexKodiConnect/contents/{+path}",
    "compare_url": "https://api.github.com/repos/croneter/PlexKodiConnect/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/croneter/PlexKodiConnect/merges",
    "archive_url": "https://api.github.com/repos/croneter/PlexKodiConnect/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/croneter/PlexKodiConnect/downloads",
    "issues_url": "https://api.github.com/repos/croneter/PlexKodiConnect/issues{/number}",
    "pulls_url": "https://api.github.com/repos/croneter/PlexKodiConnect/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/croneter/PlexKodiConnect/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/croneter/PlexKodiConnect/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/croneter/PlexKodiConnect/labels{/name}",
    "releases_url": "https://api.github.com/repos/croneter/PlexKodiConnect/releases{/id}",
    "deployments_url": "https://api.github.com/repos/croneter/PlexKodiConnect/deployments",
    "created_at": "2015-12-27T10:43:05Z",
    "updated_at": "2017-04-17T02:03:52Z",
    "pushed_at": "2017-04-16T12:24:42Z",
    "git_url": "git://github.com/croneter/PlexKodiConnect.git",
    "ssh_url": "git@github.com:croneter/PlexKodiConnect.git",
    "clone_url": "https://github.com/croneter/PlexKodiConnect.git",
    "svn_url": "https://github.com/croneter/PlexKodiConnect",
    "homepage": "",
    "size": 6735,
    "stargazers_count": 236,
    "watchers_count": 236,
    "language": "Python",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 30,
    "mirror_url": null,
    "open_issues_count": 14,
    "forks": 30,
    "open_issues": 14,
    "watchers": 236,
    "default_branch": "master"
  },
  "sender": {
    "login": "croneter",
    "id": ,
    "avatar_url": "https://avatars0.githubusercontent.com/u/<Github user id>?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/croneter",
    "html_url": "https://github.com/croneter",
    "followers_url": "https://api.github.com/users/croneter/followers",
    "following_url": "https://api.github.com/users/croneter/following{/other_user}",
    "gists_url": "https://api.github.com/users/croneter/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/croneter/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/croneter/subscriptions",
    "organizations_url": "https://api.github.com/users/croneter/orgs",
    "repos_url": "https://api.github.com/users/croneter/repos",
    "events_url": "https://api.github.com/users/croneter/events{/privacy}",
    "received_events_url": "https://api.github.com/users/croneter/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

**Comment by matthewjackowski** [comment]
Ok that helps explain the issue.  So let me clarify a bit what Txgh does.  It works by using commit information from GitHub, so it expects a webhook with commit information.  The one you sent me looks like a "ping" event, but what you want is a "push".  
![image](https://cloud.githubusercontent.com/assets/974299/25233882/3425524c-2595-11e7-8f3d-699bf0d6c440.png)

My recommendation is to give it a try with the push event, you can find an example of the expected GitHub response in the integration tests here: https://github.com/transifex/txgh/blob/master/spec/integration/payloads/github_postbody.json

While reviewing this, I noticed that it looks like GitHub has changed their interface with regard to setting webhooks up, so the current documentation and my view of "standard" is woefully out of date. :(

**Comment by croneter** [comment]
Aha, this explains everything, many thanks! Txgh was running and listening, THEN I setup the Github webhook. This leads to a Github Ping endless loop (the redeliver button). I hope to change this order later, or be able to make a git push to "overrule" the Ping.

Thanks again

**Comment by matthewjackowski** [comment]
Great!  After some further thought, it probably makes sense for Txgh to actually *do* something with the pings, maybe log a message or something.  Pretty much anything would be better than throw the obtuse key mapping error message it gave you.

**Comment by croneter** [comment]
Seems like a Ping needs to be answered by Txgh. When setting up the Github webhook, a Ping is sent. If this fails, the webhook is stuck - I can only resend the Ping. I cannot circumvent that by e.g. doing a git push (nothing is sent by the webhook then - it seems inactive as long as the ping is unsuccessful). 

I guess I could try to setup the webhook using the Github dev interface, trying to omit the ping. No time for that though in the next couple of days..

How did you manage to get your hooks working, anyway..?

**Comment by croneter** [comment]
Just to be clear - the Github webhook, as described above, is stuck in the Ping loop because Txgh returns en error 500

**Comment by matthewjackowski** [comment]
According to GitHub:
"The ping is only informational, doesn't need to be responded to in a specific way, and nothing bad will happen if you respond with an error."
https://developer.github.com/changes/2014-02-10-ping-event-for-webhooks/

Maybe you are getting a 500 error on the subsequent push webhook as well.

What I did was first validate my webhooks using something like: https://requestb.in/
Then make sure these results match the payload expectations in the rspec tests.  Assuming that is reasonable should be a good indication if your webhooks are setup correctly.

Again it might make sense to eventually add more validation of these requests, but this will take some additional thought/design.

**Comment by croneter** [comment]
My test procedure was the issue: doing an "empty" push on the Github side results in a simple Ping. If I do a meaningful commit, the txgh error above does not show. So one step further, thanks 😉 

Unfortunately, if I update the souce file `resources/language/resource.language.en_gb/strings.po` on Github, nothing happens on the txgh side:
```
[ec2-user@ip-<IP> txgh]$ bundle exec rackup -o 0.0.0.0
Puma starting in single mode...
* Version 3.8.2 (ruby 2.2.2-p95), codename: Sassy Salamander
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
I, [Sun 23-04-2017 1546 #12864]  INFO -- : Processing request at /hooks/github
I, [Sun 23-04-2017 1546 #12864]  INFO -- : processing payload from form
I, [Sun 23-04-2017 1546 #12864]  INFO -- : croneter/PlexKodiConnect
I, [Sun 23-04-2017 1546 #12864]  INFO -- : request github branch: heads/translations_transifex
I, [Sun 23-04-2017 1546 #12864]  INFO -- : config github branch: heads/translations_transifex
I, [Sun 23-04-2017 1546 #12864]  INFO -- : found branch in github request
I, [Sun 23-04-2017 1546 #12864]  INFO -- : processing resource
I, [Sun 23-04-2017 1546 #12864]  INFO -- : processing commit
I, [Sun 23-04-2017 1546 #12864]  INFO -- : processing modified file: resources/language/resource.language.en_gb/strings.po
<IP> - - [23/Apr/2017:15:46:04 +0000] "POST /hooks/github HTTP/1.1" 200 - 0.1485
```
Seems like txgh doesn't see a cause to actually update the source file. Any ideas?

txgh.config:
```
[main]
host = https://www.transifex.com

[plexkodiconnect.stringspo]
source_file = resources/language/resource.language.en_gb/strings.po
source_lang = en_gb
type = PO
file_filter = resources/language/resource.language.<lang>/strings.po
minimum_perc = 60
```

txgh.yml:
```
txgh:
  github:
    repos:
      # This name should be org/repo
      croneter/PlexKodiConnect:
        api_username: "croneter"
        api_token: "<token>"
        # Transifex project name, as below
        push_source_to: "plexkodiconnect"
        # The branch to watch. Set to 'all' to listen to all pushes.
        branch: "translations_transifex"
        # Create a repo webhook. The secret is any string of your choosing,
        # and is input during webhook creation. TXGH uses this to validate
        # messages are really coming from GitHub.
        webhook_secret: "<secret>"
        # branch to diff against (usually master)
        # diff_point: "translations_transifex"
  transifex:
    projects:
      # This name should match the transifex project name, without org name
      plexkodiconnect:
        tx_config: "/home/ec2-user/tx.config"
        api_username: "Croneter"
        api_password: "<TOKEN>"
        # This is the GitHub project name, as above.
        push_translations_to: "croneter/PlexKodiConnect"
        # protected_branches: "master","develop"
        # This can be 'translated' or 'reviewed'. To catch both actions,
        # simply remove this key.
        # push_trigger: "translated"
        # This works similarly to the GitHub webhook_secret above.
        webhook_secret: "<secret>"
```
And the detailed Github payload as an attachment:
[github-payload.txt](https://github.com/transifex/txgh/files/949815/github-payload.txt)

**Comment by matthewjackowski** [comment]
Hard to say.
I'd check a couple of things 1) make sure your source language matches what you have setup in Tx 2) it looks like you have a directory with periods in it, offhand it *should* work, but it is an 'odd' naming structure that might not be well tested and could be causing problems.

**Comment by croneter** [comment]
Got it - you were right, the source language was English, not English (UK). Thanks for your help!
